# Generated by Django 6.0.1 on 2026-01-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('carbon_score', models.IntegerField(default=50, help_text='Lower is greener')),
                ('transport_options', models.CharField(blank=True, help_text='Comma-separated transports: train,bus,bike', max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags: nature,city,coast', max_length=200)),
            ],
        ),
    ]
