# Generated by Django 5.2.7 on 2026-01-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrecord',
            name='passenger_count',
            field=models.IntegerField(default=1),
        ),
    ]
